### ISSUE TITLE
Integrate mumble-web as a Matrix/Element widget

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/mumble-web_ynh#5]
Hi,
thanks a loooot for packaging this app which will enable people to reach us muuch easier! It will soon be deployed on sans-nuage.fr 

Do you think you could add an option to integrate it with a running [synapse instance](https://github.com/YunoHost-Apps/synapse_ynh )? 
See the explanations that I do not yet understand: https://github.com/Johni0702/mumble-web/#matrix-widget

Maybe @Josue-T could help on this? 

I already have a test server running with both mumble(-web) and synapse. We could organize a test if it helps. https://audio.arn-test.noho.st/

**Comment by ericgaspar** [comment]
I took a look at the integration with Matrix. Seems to be outside the scope of this app ... As I understand it, creating a Matrix widget is done in the Riot web client or the Desktop client

**Comment by Gredin67** [comment]
yep indeed, I think we should follow these issues https://github.com/matrix-org/matrix-widget-api https://github.com/vector-im/element-meta/issues/1476
